### PR TITLE
Remove closure library

### PR DESCRIPTION
**Pull request by rixner**
As I wrote in #867, I don't think the using the closure library is worth it.  We use very few functions from it and it is not designed in a way that is friendly to modern Javascript modules.

This pull request includes replacements to the functions we actually do use (found in ```src/assert.js``` and ```src/util.js```).

The one noticeable difference is that an assertion failure now throws and ```Error``` instead of an ```AssertionError```.  It doesn't seem like the machinery to subclass ```Error``` in an ES5 compatible way that preserves the stack trace is worth it.  Especially since assertions are turned off in the distribution anyway, so this is only a development-time error.

### CODE REVIEW

**Comment by rixner** [comment]
FYI, I just tried a quick experiment, and I think this is going to make it possible to use webpack to build the dist file instead of having to have a separate file list in ```skulpt.py```.  I used ```main.js``` as an entry point, and it just built the file correctly and it runs (I didn't minify it).  I didn't run the closure compiler on it, but I think that is possible through webpack (maybe?), so we can hopefully create the distribution that way.  (The impediment before was the non-node-friendliness of the closure library.)

**Comment by rixner** [comment]
@skulpt/committers does anyone have time to take a look at this?  Thanks!

**Comment by bnmnetp** [comment]
I've built and tested on all of my tricky examples...With the exception of finding a case in image processing that exercises #875 / #868 in Chrome everything works fine.

I have no issues with removing the closure library in general either.  So unless we get an objection from someone else I can merge.

**Comment by rixner** [comment]
@s-cork you are correct, this is wrong.  Assertion failures just throw ```Error``` now.  Apparently, that's not tested, so it slipped through...

**Pull request merged**
