### PR TITLE
Asynchronous (suspendable) loading of imported modules

### PR DESCRIPTION
**Pull request by meredydd**
This change allows imported modules to be loaded asynchronously.

### CODE REVIEW

**Comment by bnmnetp** [comment]
@bzwheeler have you checked this out with the Sk.externalLibraries functionality?  Any problems?

**Comment by meredydd** [comment]
There is one issue I've discovered, and will be fixing this morning - turns
out the strategy of just attaching a traceback property to whatever gets
thrown through is not robust to things like, eg, throw(undefined);.  I'm
going to modify it to wrap everything thrown through it in an Sk.Exception
in order to attach a meaningful stack trace. Hope that's OK.

Meredydd

**Comment by meredydd** [comment]
(sorry, I made a comment here that belonged on the wrong pull request. As far as I'm concerned, this one is ready to merge.)

**Comment by bnmnetp** [comment]
Seems to work fine with Sk.externalLibraries for me.

**Pull request merged**
