### PR TITLE
Use terser rather than babel-minify

### PR DESCRIPTION
**Pull request by bennorth**
As discussed in #1231, a fresh checkout is encountering build failures, perhaps because of a change to a dependency outside Skulpt itself.  The failure is in the minify stage.  One option is to move from [babel-minify](https://www.npmjs.com/package/babel-minify) (15k weekly downloads) to a more active minify tool such as [terser](https://www.npmjs.com/package/terser) (17M weekly downloads).  This PR suggests how that move might be done.

I've reviewed [the options terser offers](https://github.com/terser/terser#api-reference) for controlling minification, and tried to pick conservative ones.  Skulpt's unit tests pass with the new minified code (except `TimeTestCase.test_strftime`, which I think is unrelated), as do the unit tests of a project of mine which is based on Skulpt.  All the same I realise this is a deep change so would welcome input from the maintainers!

### CODE REVIEW

**Comment by bennorth** [comment]
Using `terser` rather than `babel-minify` cuts down the number of dependencies a bit too.  Running
```shell
rm -r node_modules && npm install && npm list | wc -l
```
on current `master` gives 1209 entries; with this PR, that number drops to 1068.

It would also eliminate one (low-priority) `npm audit` result, for `yargs-parser`.

**Comment by s-cork** [comment]
Thanks for the updates - one thing that would be great (that we don't currently do (afaik)) would be to transpile the stdlib based on the preferred build method.

more specifically - es6 syntax is not transpiled to es5 syntax in the `stdlib` - which is becoming less problematic with the demise of IE but would still be a gotcha for users that expect a full es5 compatible build when someone runs `npm run build-es5`.

Is a mechanism for build options within the scope of this pr?

**Comment by bennorth** [comment]
(Force-pushed to rebase onto new `master`.)

**Comment by rixner** [comment]
In principle, this seems like a good idea. My question, though, is does this make it easier, harder, or the same to ultimately achieve the objective of transpiling the libraries to match the desired language level of the core? That doesn't need to be part of this pull request, but I think we should be thinking ahead (and it's well past time for adding that capability...)

**Comment by albertjan** [comment]
I think this is a good idea, because we're adopting a more widely used tool, which will obviously be better maintained. @s-cork what do you think?

**Comment by s-cork** [comment]
I'd consider this an improvement on what we currently have - it means relying on a more maintained minifier. @bennorth the error from the unittest is a package.json vs package-lock.json inconsistency. If you could update the lockfile so that the terser version matches then we can this merged.

I agree with @rixner that there's a broader discussion here about what the best build process is for the stdlib/core. But outside the scope of this pr.

**Comment by bennorth** [comment]
Thanks for looking at this @s-cork.  I can rebase onto fresh `master` and force-push, to make for a less tangled history?  There's been a new release of `terser` (v5.7.0) which I was thinking to update to at the same time.

**Comment by bennorth** [comment]
Force-pushed after rebasing onto fresh `master`.

**Comment by bennorth** [comment]
Force-pushed after rebasing onto fresh `master`.

**Review by s-cork — APPROVED** [review]
looks good to me

**Review by albertjan — APPROVED** [review]

**Pull request merged**
