### PR TITLE
Update the version number in package.json to 1.2.0

### PR DESCRIPTION
**Pull request by timmartin**
There's a tag for v1.2.0, but this hasn't been updated in the `package.json`. I think we should update this and then push an updated version to the NPM registry.

### CODE REVIEW

**Comment by albertjan** [comment]
Hey @timmartin @s-cork should we reintroduce the main.js from the original npm package? So we can do:

```
const Sk = require('skulpt');
Sk.configure()
```

instead of:

```
require('./dist/skulpt.min.js');
require('./dist/skulpt-stdlib.js');

Sk.configure();
```

**Comment by albertjan** [comment]
See this comment: https://github.com/skulpt/skulpt/issues/1022#issuecomment-636905598

**Comment by s-cork** [comment]
@albertjan seems sensible to me

**Comment by albertjan** [comment]
@timmartin can you add the `main` field  in the package.json https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main and add a `main.js` in the root that has:

```
require('./dist/skulpt.min.js');
require('./dist/skulpt-stdlib.js');

module.exports = Sk;
```

**Comment by timmartin** [comment]
Good suggestion, that will fix a major pain point I encountered when I first tried to import the library.

FWIW this PR is showing up as being an outdated branch, because I pulled the branch for this change from the `1.2.0` tag. That seemed like the most sensible thing to do because I'd expect the 1.2.0 release on NPM to include only the changes in the 1.2.0 tag and not further changes on `master` since. But if that makes the merge and deploy untidy I can rebase onto master and we can just live with the inconsistency.

**Review by albertjan — APPROVED** [review]

**Comment by bnmnetp** [comment]
If we are going to do a new release wouldn't we want to have #1092 as a part of it??  Maybe we should just do a new tag.

**Comment by timmartin** [comment]
I'm not intending this to be a new release, I'm hoping to get the release we already have made (1.2.0) into the NPM registry so that NPM users can have access to it.

**Comment by camilstaps** [comment]
@bnmnetp @albertjan is anything blocking updating the npm package right now? The outdated version there can be confusing (https://github.com/skulpt/skulpt/issues/1281).

**Comment by bnmnetp** [comment]
I'm happy to merge this.... But I think I missed the memo on what we need to do to update npm.

Would be nice to create a workflow for that piece.

**Comment by timmartin** [comment]
Someone with the necessary credentials needs to run `npm publish`. If we want, this can be done automatically from GitHub actions - I've got [a configuration file here](https://github.com/timmartin/skulpt/blob/scoped_package/.github/workflows/deploy.yml) that does the necessary deploy on any tagged git commit for my private version of Skulpt; we could do the same with mainline if we want.

**Comment by camilstaps** [comment]
@albertjan sorry for troubling you again, but do you think you could run `npm publish` (seeing as you published 1.0.0)? It would be great to have a more recent version in the repository.

**Comment by albertjan** [comment]
Done deployed master as 1.2.0 (soz @s-cork should I republish it as 1.3.0?). Thing's I've learned:

- we need to think about what we want to add to the package and add them to the `files` in package.json
- we need to remove `private: true` from package.json
- we need a command to build minified and non minified versions

What you have to do now:

- build dev and prod builds put them in `dist/`
- remove `dist/` dir from .gitignore
- remove `private: true` from package.json
- publish it

**Comment by camilstaps** [comment]
Thanks!

**Pull request merged**
