### PR TITLE
Fix issue #536

### PR DESCRIPTION
**Pull request by jedevc**
str.count('.') now first escapes all the special regex characters.

### CODE REVIEW

**Comment by albertjan** [comment]
Thank you very much for your contribution! Could you please add a test so it doesn't get broken again in the future?

**Comment by jedevc** [comment]
Sorry, new here, which dir should the test go in?

**Comment by albertjan** [comment]
In the tube atm. If you look at euther cotributing.md of hacking.rst. I
think it explains some stuff. Also look at the options for the skulpt.py
file and in the test/unit directories. Good luck!

**Comment by waywaaard** [comment]
I think, your changes should already cause a couple of failing tests. Please run `python skulpt.py -dist -u -v` to get an overview about the tests. You can also pipe the results into a text file.

Currently, skulpt uses two types of tests. The old ones compare the output of skulpt with the output of real python. The 2nd ones are real ported unit tests from cpython.

**Comment by albertjan** [comment]
All tests pass on travis. Or are there some with a forced output?

**Comment by jedevc** [comment]
@waywaaard on my machine, all those tests seem to work. Although, it does say "Tests failed on uncompressed version".

**Comment by jedevc** [comment]
And here are some tests so that it doesn't happen again.

**Comment by albertjan** [comment]
Thanks! LGTM!

**Comment by jedevc** [comment]
Awesome :)
I'd love to help more with this project - it's very clever.

**Pull request merged**
