### PR TITLE
Add frozenset to builtin function(Got things done!)

### PR DESCRIPTION
**Pull request by alexwenbj**
1. Add frozenset;
2. Add `__contains__ `to set;
3. Modify lib/keyword.py,same as the Python implementation.

### CODE REVIEW

**Comment by alexwenbj** [comment]
This PR close #1029 .

**Comment by rixner** [comment]
@alexwenbj, I haven't had a chance to look over this carefully yet, but please make sure that you add tests.  They should be unit tests that go in test/unit3/test_frozenset.py.  You probably should look at the tests in CPython (https://github.com/python/cpython/tree/master/Lib/test).  We generally copy the tests into Skulpt and then comment out the ones that don't work yet because of other missing features.

**Comment by alexwenbj** [comment]
@rixner That is why I didn't add unit tests:

1. All these frozenset functions are copy from set functions.In fact,I copy the set.js file totally then delete the unused functions from it.
2. I can't find the unit test for frozenset in CPython unit test directory.

**Comment by alexwenbj** [comment]
@rixner Add unit test cases.

**Comment by rixner** [comment]
@alexwenbj you have exposed methods to Python programs that shouldn't exist:

```
s = frozenset([1, 2, 3])
print(s)
s.frozenset_add_(4)
print(s)
```

If you need internal functions, they should just be Javascript functions, you should not wrap them with ```Sk.builtin.func```, which makes them into Python functions.  You can use ```$``` in the Javascript function name for internal-use only functions.

Also, it seems like it might be better/easier to just use ```Sk.builtin.set``` as the internal representation for frozensets.  Then in the fronzenset methods (including the constructor) you can just call the appropriate set methods.  That way you won't need to reimplement methods, you won't need to have mutation methods that shouldn't be there, etc.  This internal set won't be exposed to Python programs, so as long as you never mutate it, things should work.  Am I missing something which makes it better/necessary to replicate the behavior of sets?

Finally, I don't think you need to add a new future flag here, you should just be able to use ```Sk.__future__.python3``` to determine which representation to use.

**Comment by alexwenbj** [comment]
> @alexwenbj you have exposed methods to Python programs that shouldn't exist:
> 
> ```
> s = frozenset([1, 2, 3])
> print(s)
> s.frozenset_add_(4)
> print(s)
> ```
> 
> If you need internal functions, they should just be Javascript functions, you should not wrap them with `Sk.builtin.func`, which makes them into Python functions. You can use `$` in the Javascript function name for internal-use only functions.
I think this method will not and should not be invoked by programmers, cause when you use the dir():
```
f = frozenset([1, 2, 3])
print(dir(f))
```
what you get:
`['__contains__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__iter__', '__le__', '__lt__', '__ne__', '__new__', '__repr__', '__setattr__', '__str__', 'copy', 'difference', 'intersection', 'isdisjoint', 'issubset', 'issuperset', 'symmetric_difference', 'union']`
you won't get the frozenset_add_ method. I guess the function naming way with a "_" in the end is a way like $?

> 
> Also, it seems like it might be better/easier to just use `Sk.builtin.set` as the internal representation for frozensets. Then in the fronzenset methods (including the constructor) you can just call the appropriate set methods. That way you won't need to reimplement methods, you won't need to have mutation methods that shouldn't be there, etc. This internal set won't be exposed to Python programs, so as long as you never mutate it, things should work. Am I missing something which makes it better/necessary to replicate the behavior of sets?
> 
Yes, maybe it is a better way. But about the mutation methods, see my answer above.
> Finally, I don't think you need to add a new future flag here, you should just be able to use `Sk.__future__.python3` to determine which representation to use.
This is just like the set implementation.

**Comment by rixner** [comment]
@alexwenbj, I ran that program and it mutated the frozenset by adding 4 to it.  Did you run it?

**Comment by alexwenbj** [comment]
> @alexwenbj, I ran that program and it mutated the frozenset by adding 4 to it. Did you run it?

What I mean is the users will not know the frozenset_add_() method if they don't read the code, because the dir() will not expose the method to them.

**Comment by rixner** [comment]
Regardless of whether users will see those methods when they use ```dir```, they do not belong there.  They are internal functions so should not be exposed, and there is no advantage of doing so.  Just make them internal functions.

```
Sk.builtin.frozenset.frozenset$add = function (self, item) {
    self.v.mp$ass_subscript(item, true);
    return Sk.builtin.none.none$;
};
```

That way, you can call them normally, they won't be exposed to Python, and you can use whatever helper functions you want.  However, it also seems like functions like this are completely unnecessary and you could just put the one line of code to call ```mp$ass_subscript``` directly where you need it.

**Comment by alexwenbj** [comment]
@rixner Sorry,I am not familiar with the base mechanism of the method. When I modified the `Sk.builtin.frozenset.prototype["frozenset_difference_update_"] `to `Sk.builtin.frozenset.frozenset$difference_update` and invoked it with `Sk.builtin.frozenset.frozenset$difference_update(null, new_args);`, or copied the code inside difference_update to the invocation place, the result is not correct.

**Comment by rixner** [comment]
If you construct new_args in the same way, I assume you would still need to call it as ```Sk.builtin.frozenset.frozenset$difference_update.apply(null, new_args)``` to call it with an array.  But, in that case, it probably makes more sense to change it to just take an array as an argument.  Or better yet, inline the code.  I'm not sure why inlining it wouldn't work, that must just be a bug in the way you inlined it, right?

**Comment by alexwenbj** [comment]
`Sk.builtin.frozenset.prototype["frozenset$update"]` definition + `Sk.builtin.frozenset.frozenset$update.func_code.apply(null, new_args);` invocation = Cannot read property 'func_code' of undefined

`Sk.builtin.frozenset.prototype["frozenset$update"]` definition + `Sk.builtin.frozenset["frozenset$update"].func_code.apply(null, new_args);` invocation = Cannot read property 'func_code' of undefined

`Sk.builtin.frozenset["frozenset$update"] = function (self, other)` definition + `Sk.builtin.frozenset["frozenset$update"].func_code.apply(null, new_args);` invocation = Cannot read property 'func_code' of undefined

`Sk.builtin.frozenset["frozenset$update"] = function (self, other) ` definition + `Sk.builtin.frozenset.frozenset$update(null, new_args);` invocation = TypeError: '<invalid type>' object is not iterable (Because in passed the array into forzenset$update() function, not arguments.)

I think, maybe let this PR open until someone can help improve it.
To the ones need the frozenset, it is a not so bad alternative solution.

**Comment by alexwenbj** [comment]
@rixner I have removed all the unnecessary python methods from the code.Please review them again.

**Comment by rixner** [comment]
The operators should have type checks for Python 3.  See #1053 - you should just be able to copy those checks here and add similar tests.  May as well put them in now, rather than leaving them for another pull request.

**Comment by alexwenbj** [comment]
@rixner Add the test cases.

**Comment by rixner** [comment]
The operator error messages all have "&" instead of the correct operator.  Otherwise, this looks good! Fix the messages and I'll merge this. Thanks @alexwenbj.

**Comment by alexwenbj** [comment]
@rixner Corrected them.Thank you for your kindness and patient.

**Pull request merged**
