### PR TITLE
Minor Turtle changes

### PR DESCRIPTION
**Pull request by ahuhn**
I'm running multiple instances of skulpt on a page, so I added code to let me stop a turtle animation when the next one starts.  (Feature addition)

I also added e.preventDefault in a few places to help out the onkey handling in turtle code.  (Bug fix)

This is my first pull request, so please feel free to give me feedback.

Thanks!

### CODE REVIEW

**Comment by albertjan** [comment]
@ahuhn couldn't you call `e.preventDefault` in the implementation of the your eventhandler? Other implementors might want their click events to bubble up.

**Comment by ahuhn** [comment]
I do have a file for my own modifications, and I could put the e.preventDefault there, but I think this change might be useful for others.  It only applies to keypresses, not clicks, and it only happens when the turtle canvas is in focus and there is a turtle screen keyhandler for that key.  You don't want the page moving around under you.  Here's some sample code, and the issue shows up if you paste it into the top box of http://www.skulpt.org/.  

That said, I see the overall place that you are coming from.  If this change is in place, it can't be worked around from the outside whereas e.preventDefault can be added from the outside.  Should I take it out?

```
import turtle

wn = turtle.Screen()                 # Get a reference to the window
wn.bgcolor("lightgreen")             # Set the background color
tess = turtle.Turtle()               # Create our favorite turtle

print "Click on the canvas then press the up arrow key."

# The next four functions are our "event handlers".
def h1():
    tess.forward(30)

def h2():
    tess.left(45)

def h3():
    tess.right(45)

def h4():
    wn.bye()                        # Close down the turtle window

# These lines "wire up" keypresses to the handlers we've defined.
wn.onkey(h1, "Up")
wn.onkey(h2, "Left")
wn.onkey(h3, "Right")
wn.onkey(h4, "q")

# Now we need to tell the window to start listening for events,
# If any of the keys that we're monitoring is pressed, its
# handler will be called.
wn.listen()
wn.mainloop()
```

**Comment by albertjan** [comment]
Sounds reasonable. You're right that you don't want the page to move around when you use the keys. @bzwheeler do you concur?

**Comment by bnmnetp** [comment]
I certainly concur if this fix prevents the page from scrolling when up and down arrow keys are pressed.

**Comment by albertjan** [comment]
Well lets merge it's easily enough reverted.

**Pull request merged**
