### PR TITLE
HACKING.md updated typos

### PR DESCRIPTION
**Pull request by jmunsch**
Just updated a couple typos in HACKING.md

And I saw that there was a need for some documentation to be done? Are there any instructions on how to do this? I also saw the `gh-pages` branch. I could help out there?

Related: 
- https://github.com/skulpt/skulpt/issues/182
- https://github.com/skulpt/skulpt/issues/454

Although after further exploration, it looks like it has moved to: http://www.skulpt.org/static/developer.html

Very cool project ya'll.

### CODE REVIEW

**Comment by albertjan** [comment]
@eah13 Can you tell @jmunsch about the new site? :smile: 

@jmunsch It hasn't moved there I think thats even older.

**Comment by eah13** [comment]
@jmunsch see #467 for discussion and the current state of the branch deployed at http://elliotthauser.com/skulpt/

Help welcome.  I've gotten behind on my contributions to it but am still PRP for it.  If you'd like to help with the new Jekyll-based site happy to give you a run-down.  We'd like as much of the documentation to be automated via JSDocs like this: http://elliotthauser.com/skulpt/docs/

**Comment by jmunsch** [comment]
@albertjan I see what you mean. Thanks!

@eah13 I'll follow the setup instructions and do some exploration of the branch.

**Comment by bnmnetp** [comment]
Yes, the developer.html under docs/static is old, and will be removed once the gh-pages branch goes live.

I don't think we are too far away from a gh-pages based site either.   For me the top priority would be to revamp the examples we show on the front page.

1.  A better turtle example
2.  A processing example
3.  A pygal example
4.  A good demonstration of Suspensions -- maybe a turtle example with events?
5.  A couple of text based examples that demonstrate generators and inheritance?

The rest of the todo list could follow in an iterative way, but getting better examples and the improved docs would be  huge step.

**Comment by bnmnetp** [comment]
Also, @jmunsch I would be interested in knowing what you would find helpful to add to the HACKING.md document?   My thinking is that document is the conceptual overview, and task oriented documentation with the details provided by the generated docs.

**Comment by jmunsch** [comment]
@bnmnetp

On first impression I was expecting a straight forward walk through on how to start hacking. However after reading the HACKING.md I was mostly overwhelmed since finding more in depth info on the helper functions is tied to the source, and although I was warned, I was getting stuck in the details of trying to decipher the transpiled javascript.

Structure wise I would have found it more accessible jumping straight into "adding a module" or the "hello world" and then slowly revealing the building blocks. So like just start out with here's the tools, here is what they do, and to start hacking, copy this into such and such a file, run this, run that, congrats you just did something cool, and then provide the details, links, and behind the scenes. So perhaps a 10,000 ft overview.

Overall more links on how to piece together how SK works ( from the generated docs) would have been super helpful. Some examples:

- Link back to the prerequisite sections for the scroll happy, like myself, I tend to read in a non-linear sort of way.
- "Development Workflow" a link to "builtindict.js".
- "Default Parameters": Differentiate how the Javascript sorted function is being converted to Python. Links to the ```SK.builtin``` ( http://elliotthauser.com/skulpt/docs/Sk.builtin.html ) 
- "Debugging" Link back to ```./m``` expand on what it is and does?
---
It would be really great to see examples of turtle and processing using suspensions.

**Pull request merged**
