### PR TITLE
Integer division

### PR DESCRIPTION
**Pull request by ahuhn**
This does not pass tests, but I'm opening a pull request to make discussion easier.

### CODE REVIEW

**Comment by ahuhn** [comment]
This bug is more extensive.  I'm looking into it more.

**Comment by albertjan** [comment]
@ahuhn could you add a test for this case too?

**Comment by ahuhn** [comment]
@albertjan Is that a good location for the tests?

**Comment by waywaaard** [comment]
Yes, it is. Currently, we cannot port all of cpython's unit tests due to some of skulpts restrictions.

**Comment by albertjan** [comment]
LGTM @skulpt/committers do you concur?

**Comment by bnmnetp** [comment]
I would just want to make sure this still works correctly when the Sk.python3 flag is true.

**Comment by albertjan** [comment]
Oh good catch never thought of that. @waywaaard what do you think?

**Comment by ahuhn** [comment]
I wasn't sure where to put the tests, but I did test it by hand:

```
print(3/2 == 1.5, "\t3/2 should be 1.5")
print(3//2 == 1, "\t3//2 should be 1")
print(3/2.0 == 1.5, "\t3/2.0 should be 1.5")
print(3//2.0 == 1.0, "\t3//2.0 should be 1.0")
print(-3/2 == -1.5, "\t-3/2 should be -1.5")
print(-3//2 == -2, "\t-3//2 should be -2")
print(-3/2.0 == -1.5, "\t-3/2.0 should be -1.5")
print(-3//2.0 == -2.0, "\t-3//2.0 should be -2.0")
```

Is there a way to change which tests run based on the Sk.python3 flag?

**Comment by albertjan** [comment]
@ahuhn the tests are in the correct place. But there's a flag in skulpt that changes somethings around so it acts a bit more like python3. You can just set it globally just add this to your javascript: `Sk.python3 = true`

**Comment by ahuhn** [comment]
I tested the lines above by changing the Sk.python3 flag in the javascript to test it by hand, but I am not sure where to add the tests in the automated tests.  The file test_int.py should be different for python2 and python3.

**Comment by albertjan** [comment]
There are no automated tests for `Sk. python3`

**Comment by albertjan** [comment]
@bnmnetp I'm satisfied, this doesn't break the python3 int/int division.

**Pull request merged**
