### PR TITLE
fix comment for importBuiltinWithBody

### PR DESCRIPTION
**Pull request by albertjan**
@rixner yeah this comment was completely wrong I copied to much there 😄

### CODE REVIEW

**Comment by rixner** [comment]
Looks much better to me!

**Comment by rixner** [comment]
I'm also just now noticing that ```Sk.builtin.property``` is still in ```builtin.js``` and it throws a ```NotImplementedError```.  Shouldn't that be removed?

**Comment by albertjan** [comment]
Oh yeah good one. I'll add that to this PR.

**Comment by LeszekSwirski** [comment]
:+1:

**Pull request merged**
