### PR TITLE
Discovered how to import and use python functions from python modules…

### PR DESCRIPTION
**Pull request by bnmnetp**
… inside javascript modules.

### CODE REVIEW

**Comment by bnmnetp** [comment]
I question whether some of these documentation changes need multiple reviewers, but I'll follow the rules for now.

**Comment by waywaaard** [comment]
I could have answered that question. Anyways, I think we should also add an example that shows how to create a new instance of a class. 

```python
var io = Sk.importModule("io", false, false);
var stdin = Sk.misceval.callsim(io.$d["TextIOWrapper"]);
```

Or at least mention it somewhere that this is also possible. You do not need to call the ```__init__``` on the object, just the class name.

**Comment by bnmnetp** [comment]
Good example, I'll add it to the PR.

@waywaaard do you folllow the gitter discussion at all?   I think one problem is that most of the communication between developers only happens on the github issues/PRs.   Which is great for that, but I don't feel like other developers really monitor the google group (it very low traffic) so there is not an obvious place to ask such a question.

**Comment by waywaaard** [comment]
@bnmnetp Yes I do sometimes, however I have been busy last days -> business trip.

**Comment by eah13** [comment]
:+1: looks good to me.  @waywaaard's example is a helpful addition.

Going to go ahead and merge.  Personally I think docs changes like this do well to be PR'd, for helpful suggestions if nothing else.  A single reviewer could be fine too.  

If we don't want to have them go thru review then the wiki is the right answer.  Makes sense to me to have them in the repo as opposed to a wiki page for now so they're in the repo when cloned.

**Pull request merged**
