### PR TITLE
Profiling and timing commands

### PR DESCRIPTION
**Pull request by mchat**
I've added a few profiling tools to skulpt.py which I have found useful in assessing/improving performance in Skulpt.

## profile
```{program} profile [filename.py] [output]```

Run the Python file (or the entire test suite, if no file specified) using the d8 engine with the profiling flag set, which saves tick output in v8.log. Processes  v8.log using the d8 tick processing tools and outputs the results to the output file (or stdout, if no file specified).

Sample usage:

| Command | Result |
| --- | --- |
| `./skulpt.py profile my_profile` | Profile test suite and output processed results to my_profile |
| `./skulpt.py profile test/run/t00.py` | Profile test/run/t00.py and output processes results to stdout |
| `./skulpt.py profile temp.py temp_profile` | Profile temp.py and output processed results to temp_profile |

## time
```{program} time [filename.py] [iter=1]```
Computes the average runtime of a Python file (or entire test suite, if no file specified) over iter number of trials.

Sample usage:

| Command | Result |
| --- | --- |
| `./skulpt.py time` | Report the runtime of the entire test suite |
| `./skulpt.py time 5` | Report the average runtime of the test suite over 5 trials |
| `./skulpt.py time temp.py` | Report the runtime of temp.py |
| `./skulpt.py time temp.py 20` | Report the average runtime of the test suite over 20 trials |

**Caveat:**
I have used these tools mostly on Mac, briefly on Linux, and have not yet tested them on Windows. This does make changes to the jsengine variable is set, so should be carefully tested before being accepted.

### CODE REVIEW

**Comment by rixner** [comment]
Has anyone had a chance to take a look at this?

**Comment by albertjan** [comment]
I looked at it but haven't tried it out. We should pull this in it'll give us much needed insight into performance. I can't try it out atm cause I'm on vacation :)

**Comment by rixner** [comment]
I think that a few people need to at least make sure that they can run it properly first.  It works for @mchat on a Mac, it works for me on Linux (Ubuntu and Mint).  But, it has not been tested on Windows yet, as we don't ever use Windows.

I agree, though, that this will help us to be more cognizant of performance issues, so I view this as an important addition to Skulpt.

**Comment by waywaaard** [comment]
I am working on windows, I have more time next week to test the commands.

**Comment by rixner** [comment]
@bnmnetp this one has been sitting here for 3 weeks.  @mchat has another pull request waiting that is contingent upon this one being accepted.  Can we officially assign someone to look at this and make a decision.  I have looked at it, but I really feel that someone else needs to do so as well, for the reasons I stated above.

**Comment by waywaaard** [comment]
My bad, I am going to test this. The end of the semester with the exams just takes all my time currently.

**Comment by albertjan** [comment]
If you don't have time @waywaard I say just pull it in. We'll fix any windows oopsies later. Most of us use mac/linux anyway.

**Comment by bnmnetp** [comment]
@rixner I did not know this was holding up another PR.  It works for me, and if we run into problems with Windows, then we can do a bug fix PR to address that if it comes up.

With no objection, I will accept later today.

**Pull request merged**
