### PR TITLE
fix a typo.

### PR DESCRIPTION
**Pull request by alexwenbj**
fix a pypo.

### CODE REVIEW

**Comment by s-cork** [comment]
I wonder if we should also remove this from the `builtindict.js` in python 3 mode since it's not available in py3?

**Comment by alexwenbj** [comment]
> I wonder if we should also remove this from the `builtindict.js` in python 3 mode since it's not available in py3?

Yes, I think it should be removed from py3.

**Review by bnmnetp — APPROVED** [review]
This LGTM, but @alexwenbj we need to fix the merge conflicts.  Once those are done we are ready to merge.

**Comment by meredydd** [comment]
Hi @alexwenbj can you rebase this so we can get it merged?

**Comment by alexwenbj** [comment]
Sorry, I didn't realize the conflicts and resolved late. Get things done now. @meredydd

**Comment by s-cork** [comment]
added a small commit to make sure unichr is a py function and get's added back in the switch from py3 to py2.

**Pull request merged**
