### PR TITLE
add deque to collections

### PR DESCRIPTION
**Pull request by alexwenbj**
Implement collections deque.

### CODE REVIEW

**Comment by alexwenbj** [comment]
Sorry, fixed it now. Wrongly delete // in comment lines. @bnmnetp

**Comment by alexwenbj** [comment]
Temporarily close to wait for adding unit tests.

**Comment by alexwenbj** [comment]
I don't know why the 2 test cases failed, In my own build,all the test cases are success:
```
Test threw exception in  TestBasic.test_maxlen  (ExternalError: TypeError: iterable.tp$iter is not a function on line 33)
Test threw exception in  TestBasic.test_maxlen_zero  (ExternalError: TypeError: iterable.tp$iter is not a function on line 51)
```
So close it, maybe someone can help to figure it out.

**Comment by bnmnetp** [comment]
@skulpt/committers This is like the tokenize change we just pulled.  quite self contained.  And it would sure be nice to start clearing this backlog.

**Pull request merged**
