### PR TITLE
fix:decode escape character

### PR DESCRIPTION
**Pull request by Lifan1998**
@albertjan 
I found the reason for the test failure:
```
String.fromCharCode(parseInt(d0 + d1, 16))
```
Error:
```
decodeURIComponent(escape(s));
```

eg:
```
i = parseInt('e'+'9',16);
console.log(String.fromCharCode(i));
/* Error: URI malformed */
// console.log(decodeURIComponent(escape(String.fromCharCode(i)))) 
s = unescape(encodeURIComponent(String.fromCharCode(i)))
console.log(s);
console.log(decodeURIComponent(escape(s)))
```

when met `\x**` or `\u****`, `String.fromCharCode(parseInt(d0 + d1, 16))` return an unencoded string.but the method return a decoded string.

### CODE REVIEW

**Comment by albertjan** [comment]
Nice work!

**Comment by albertjan** [comment]
Can you add this test to your branch? https://github.com/skulpt/skulpt/pull/873/commits/8c09469e3793a9d7bf92ed14126f3e95ed151aaf

**Comment by albertjan** [comment]
@skulpt/committers merge at will! 😄

**Comment by meredydd** [comment]
Nicely done, @lifan!

**Pull request merged**
