### PR TITLE
Tweaking build (jscs and jshint)

### PR DESCRIPTION
**Pull request by albertjan**
As talked about in #415 adds stricter rules to jscs and shows versions on travis so you can compare to your local env.

### CODE REVIEW

**Comment by albertjan** [comment]
Don't worry I'll squish these commits later :smile:

**Comment by albertjan** [comment]
@bnmnetp I didn't force the versions but print them in the build so you know which version is used on travis.

**Comment by bnmnetp** [comment]
Thanks, that will be helpful.

**Comment by bnmnetp** [comment]
@albertjan -- This is ready for review?

**Comment by albertjan** [comment]
yes it is :+1:

**Comment by bnmnetp** [comment]
Ugh, this is going to create merge conflicts for all the other outstanding PR's

**Comment by albertjan** [comment]
It's ok if you want to wait a bit, for some big PR's. I'm ok with rebasing this a few times.

**Comment by albertjan** [comment]
@bnmnetp do we want to merge this now all the big PR's have been merged

**Comment by bnmnetp** [comment]
Yes. Rebate and we can get it in.

**Comment by albertjan** [comment]
I assume you mean rebase :smile:. I allready rebased it.

**Comment by bnmnetp** [comment]
LOL on my phone without my reading glasses

**Comment by bnmnetp** [comment]
@LeszekSwirski @meredydd @rixner @bzwheeler @waywaaard 

I just want to draw everybody's attention to this PR, as it reformats the position of braces on else statements to get in line with our style guidelines.  So, this touches in a (very harmless way) a lot of code, that may cause conflicts in some of our open branches.

But, I think we've got the major PR's accepted, and this one has been waiting in the queue for the last batch to clear.

Hopefully this will be the last change like this that touches a bunch of code.  I know it kind of messes up the ``git blame`` output for cosmetic purposes only, which I don't particularly like.  But I think its good to get our code consistent.


Brad

**Pull request merged**
