### PR TITLE
Betteriter  -- Fixes 469

### PR DESCRIPTION
**Pull request by bnmnetp**
All tests except for the dict update unit test test pass.  Not sure why but there is a comment about Skulpt previously not supporting something with iteration.  So that seems likely.  @rixner any ideas?

### CODE REVIEW

**Comment by bnmnetp** [comment]
Well, there is more broken than I thought.  I'll try to sort this out in the morning.

**Comment by waywaaard** [comment]
It seems that the exception, that is maybe thrown in ```__getitem__``` is swallowed.

You can test it with:

```python
class badseq(object):
    def __iter__(self):
        return self
    def __next__(self):
        raise Exception()

{}.update( badseq())

class FailingUserDict:
    def keys(self):
        class BogonIter:
            def __init__(self):
                self.i = ord('a')
            def __iter__(self):
                return self
            def __next__(self):
                if self.i <= ord('z'):
                    rtn = chr(self.i)
                    self.i += 1
                    return rtn
                raise StopIteration
        return BogonIter()
    def __getitem__(self, key):
        raise Exception

{}.update(FailingUserDict())
```

**Comment by rixner** [comment]
@bnmnetp, I think I dealt with the exceptions correctly now.

**Comment by rixner** [comment]
I also think that ```iteridx``` needs to be turned into a Python object before it is passed to ```__getitem__```.

**Comment by bnmnetp** [comment]
OK, I have a cleaned up and fully working version now, that is much closer to the CPython version.

**Comment by bnmnetp** [comment]
If I can get an LGTM I would like to accept both 473 and 475 simulataneously.  I uncommented @rixner's tests and made one small change in his code (See the PR) to make these two play nicely together.

**Comment by albertjan** [comment]
Other then my comment it looks good to me :smile:

**Comment by albertjan** [comment]
Euhm @bnmnetp did you see my comment?

**Comment by bnmnetp** [comment]
Yes, good catch.  It was fixed in the push I just did.

**Comment by albertjan** [comment]
Ah ok :smile:

**Comment by bnmnetp** [comment]
It was kind of cool that since the two PR's were co-dependent, I could merge and accept both of them together.

**Comment by rixner** [comment]
Wait, shouldn't you have used ```PyObject_LookupSpecial_``` to find the dunder methods instead of ```tp$getattr```? Didn't we just decide that was the right way of doing things?

**Comment by bnmnetp** [comment]
You are probably right.  I was just following the lead of the existing code and not thinking hard enough.

**Comment by rixner** [comment]
Also, is ```Sk.builtin.checkIterable``` now "broken"?

(This is great, by the way!  These are small things that can easily be fixed.)

**Comment by bnmnetp** [comment]
Well, looking at the code, and based on what I know, I would say that it was always broken.  But now I might know enough to fix it.

**Pull request merged**
