### PR TITLE
updated datetime module

### LINKED ISSUE #1250: datetime needs an update
cpython now has a pure python implementation of the datetime module
Skulpts implementation is minimal and incomplete since it's taken from an early version of pypy.

now that we have bytes we might be able to port cpython's implementation (with some adjustments to support python 2.7). 

I'm currently working on this and hope to have a pr ready soon.

I might even see if i can implement `strptime` (at least partially).

Turning this into an issue incase anyone else is working on this already.

### PR DESCRIPTION
**Pull request by s-cork**
here's an updated version of the datetime module.

this is based on the #1240 pr since datetime classes uses slots for classes it seemed to make sense.

I took the current cpython pure python implementation of the datetime module and made some tweaks for backward compatibility of python 2.7.

I've incorporated tests from cpython and commented out tests that weren't relevant or that didn't pass.

---

For the relevant commits see the last 6 commits in this pr.
be1e9d5: float as_integer_ratio - required in the datetime implementation
5fa5843: adjust struct_seq for time module to allow tm_gmtoff and tm_zone
5fc1666: datetime tests from cpython
4576fdd: adjusted datetime tests for skulpt
84505f8: cpython's pure python implementation of datetime
53e9c25: adjusted datetime module for skulpt

At the moment the datetime tests take 25 seconds on my machine and the whole of unit 3 tests take 100 seconds!
This seems a little excessive - I can look to reduce iterations for tests that are causing the bottle neck perhaps.

I also could look to rewrite the datetime module from pure python into javascript.
This would improve the speed of the module - but may reduce the maintainability. Thoughts?

If this pr is merged we may want to consider the size of pure python implementations in the `skulpt-stdlib` - The datetime module is big! 
Perhaps we can look to do some minification of python files at the same time that we minify the javascript stdlib files.

--- 

This pr doesn't implement `strptime` - it seemed like that should be a separate pr.

closes #1250

### CODE REVIEW

**Comment by alexwenbj** [comment]
Great job!
BTW, could you please merge all these new prs(slots/yield from/metaclass etc.) to your own 1092/all-changes repo? So I can use it to test in my env.Thank you.

**Comment by s-cork** [comment]
@alexwenbj i've updated that branch for you.

**Comment by alexwenbj** [comment]
@s-cork Thank you. I will have a try soon.

**Comment by s-cork** [comment]
super-seeded by #1254

**Pull request closed without merging**
