### PR TITLE
unichr now working

### PR DESCRIPTION
**Pull request by JohnDenker**
Start with the demonstration:  Lots of fancy chars, generated by unichr(...)
   http://www.av8n.com/skulpt/demo/unichr.html

Heretofore, unichr() was not implemented.
This pull request provides the implementation.

I have tested this with firefox, chrome, and nodejs.

### CODE REVIEW

**Comment by albertjan** [comment]
Hey @JohnDenker thank you for your contribution! Could you add a unittest so we ensure this will keep working in the future :smile:. Thanks!

**Comment by albertjan** [comment]
see here for examples: https://github.com/skulpt/skulpt/tree/master/test/unit

**Comment by JohnDenker** [comment]
Added a new commit to the pull request ... now including a unit test.

**Comment by albertjan** [comment]
LGTM @skulpt/committers merge at will (if you concur ofcourse)

**Comment by JohnDenker** [comment]
Better error handling;  unit test now checks error cases.

**Comment by albertjan** [comment]
@skulpt/committers I took your silence for approval :smile:

**Pull request merged**
