### PR TITLE
Unittest fixes

### PR DESCRIPTION
**Pull request by bnmnetp**
assertRaises did not take the correct parameters.

### CODE REVIEW

**Comment by albertjan** [comment]
Looks good to me. @bnmnetp you feel this can be merged with one review?

**Comment by bnmnetp** [comment]
Yes, I think this is pretty safe.  Other branches can now either use assertRaises, or if they worked around the old bad one they will have to update any assertRaises unit tests to do it the right way.

**Comment by rixner** [comment]
Does ```assertRaises``` work correctly?  I'm not sure ```else``` clauses on ```try/except``` blocks work correctly in Skulpt.  I am seeing ```No error``` on code that clearly threw an exception.

**Comment by bnmnetp** [comment]
@rixner, do you have an example for me? The no error part appeared to be working fine in my tests.  In other words, failing on a non error when there should have been one.  But I have not done extensive unittests for the unittest package.

**Comment by rixner** [comment]
I screwed something up while I was trying to get the tests to run. It 
seems to work fine.  Sorry about that.

**Pull request merged**
