### PR TITLE
Feature/add isqrt function

### PR DESCRIPTION
**Pull request by BioMedTech**

### CODE REVIEW

**Comment by s-cork** [comment]
Have you checked this for negative values?
What about for integers larger than `Number.MAX_SAFE_INTEGER`
Worth checking out the tests in cpython and including more of them here. 

https://github.com/python/cpython/blob/e799aa8b92c195735f379940acd9925961ad04ec/Lib/test/test_math.py#L982

**Comment by s-cork** [comment]
@BioMedTech - are you planning on adding to this PR - if not we should close it.

**Comment by BioMedTech** [comment]
@s-cork, yes, I'm working on it currently. If something I'll let you know

**Comment by s-cork** [comment]
superseded by #1373

**Pull request closed without merging**
