### PR TITLE
Redirectable stdout and in

### PR DESCRIPTION
**Pull request by albertjan**
This PR adds the ability to redirect stdin and out. It handles stdin and out as "real" files. the sys module now has `stdin`, `__stdin__`, `stdout` and `__stdout__`. And I've added the `StringIO` module, so you have something to write to and read from.

### CODE REVIEW

**Comment by albertjan** [comment]
oh yeah this also makes imports from files in directories work.

**Comment by albertjan** [comment]
@skulpt/committers any of you have some time to look at this in the near future?

**Comment by waywaaard** [comment]
PR is fine :+1:

**Comment by eah13** [comment]
:+1: this is already in production on trinket :)

**Pull request merged**
