### PR TITLE
Fix Counter.most_common tests.

### PR DESCRIPTION
**Pull request by rixner**
Pull commit from #1044 so we can merge it quickly.

Make unit test allow arbitrary ordering of elements with the same count for Counter.most_common.

### CODE REVIEW

**Comment by bnmnetp** [comment]
@skulpt/committers -- I'm going to merge this one today.

We have developed quite a backlog of PRs.  Any suggestions for how we deal with this?  Should we promote some new committers based on some of the folks who have been actively working and submitting lately?

I hate to see these linger as we want encourage participation and improvements.

**Comment by meredydd** [comment]
I would strongly support giving @s-cork committer status; he's been doing some great stuff.

I'm sorry I haven't been much help for the last couple of months; I'll be circling back at some point but Anvil is working on some big non-Skulpt things right now...

**Comment by rixner** [comment]
I agree.  @s-cork should be given committer status.

I apologize for not being more active.  Too many things going on.  I wish I had more time to be spending on Skulpt...

**Comment by albertjan** [comment]
@bnmnetp I agree lets add @s-cork 😄 lets also add him to @skulpt/committers while you're at it. 

@s-cork for when you've been added. We require at least 2 reviewers of this group to agree on a PR, unless it's a small fix. Let's see if we can whittle down the list of PR's a little. 😄

**Pull request merged**
