### PR TITLE
Change all uses of performance to window.performance

### LINKED ISSUE #625: Cannot use time module ("performance" not defined)
I've received a few second-hand reports of a Skulpt-based application failing with `ExternalError: ReferenceError: Can't find variable: performance on line 50`. This doesn't occur on new versions of Firefox (e.g. 48) or Chrome (e.g. 51), but it sounds like it does occur on some older (unknown) versions of Safari, and possibly also some versions of Internet Explorer.

I suspect the problem is that those browsers don't support `window.performance`, and Skulpt is dying when it tries to use it. In `time.js`, there are a few checks along the lines of

``` js
if (performance && performance.now) {
}
```

which should probably be

``` js
if (window.performance && window.performance.now) {
}
```

### PR DESCRIPTION
**Pull request by j-f1**
Fixes #625.

### CODE REVIEW

**Comment by waywaaard** [comment]
Seems good for me. (I suggested the change :P)

The PR also removes some trailing whitespaces.

**Comment by j-f1** [comment]
@waywaaard Should I put the trailing whitespace back?

**Comment by albertjan** [comment]
that won't be necessary

**Comment by waywaaard** [comment]
@albertjan You can also make "real" reviews now on github. See the **Files Changed** Tab.

**Pull request merged**
