### PR TITLE
Processing ectomy

### PR DESCRIPTION
**Pull request by albertjan**
removes old processing and adds global javascript properties 😁

### CODE REVIEW

**Comment by bnmnetp** [comment]
Is there a replacement processing forthcoming or are your just trying to slim down the code base?

**Comment by albertjan** [comment]
Drat! this was supposed to stay my secret project for a while 😄. To be continued! I promise!

**Comment by bnmnetp** [comment]
So you are saying this is Deferred ? 😄

**Comment by dsblank** [comment]
Look forward to seeing the secret project! Processing with Python is the cat's meow!

**Pull request closed without merging**
