### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by rixner**
This pull request fixes four small things:

1) Conversion of floats with a trailing 0 to strings.
2) Conversion of very small floats to ints.
3) Simplify the set iterator so that no extraneous list is created.
4) Add sq$contains to set, to massively speed up "in" tests on large sets.

### CODE REVIEW

**Comment by albertjan** [comment]
@mchat good to see you're back :smile:. I don't want to nag @rixner but you didn't even wait for @travis-ci to finish the build. I think it's best people don't merge their own PR's.

**Comment by albertjan** [comment]
Sorry that sounded a bit harsh :smile:.

**Comment by rixner** [comment]
@albertjan you're fine.  The criticism is fair.  When I create a pull request, it dumps me right on the page that allows me to accept it.  This time, I impulsively just did it, as Brad has been doing a lot, so I figured I'd save him from this one.  I'll return to being more disciplined in the future.

(As a minor point in my defense, both @mchat and I always try to very carefully make sure we don't break anything when I/we create a pull request.)

**Comment by bnmnetp** [comment]
At the moment, @rixner and I are the only two that have commit authority for the whole repository.

I am the worst offender when it comes to commits.  Too often I commit directly to master without even bothering with a PR, this is especially true for small bug fixes.  I do try to do my work in my own repository, or on a branch for bigger projects.

But, it does raise an issue that has been nagging at me for a while now.   Mainly I would like to get more people reviewing, commenting, and blessing PRs.  I would like to have a wider discussion about this, so I've opened issue  #414

**Pull request merged**
