### PR TITLE
rename files to follow the module/package rules

### PR DESCRIPTION
**Pull request by bnmnetp**
I think this will help preserve sanity, and it also aligns us with the CPython rules regarding modules and packages.

```
 rename src/lib/{document/__init__.js => document.js} (100%)
 rename src/lib/{image/__init__.js => image.js} (100%)
 rename src/lib/{math/__init__.js => math.js} (100%)
 rename src/lib/{operator/__init__.js => operator.js} (100%)
 rename src/lib/{processing/__init__.js => processing.js} (100%)
 rename src/lib/{random/__init__.js => random.js} (100%)
 rename src/lib/{re/__init__.js => re.js} (100%)
 rename src/lib/{string/__init__.js => string.js} (100%)
 rename src/lib/{time/__init__.js => time.js} (100%)
 rename src/lib/{turtle/__init__.js => turtle.js} (100%)
```

### CODE REVIEW

**Comment by bnmnetp** [comment]
Just as a test, on a local branch I merged @waywaaard 's big PR and then merged this one after it. There were no merge conflicts created on the modules.  So I think this is quite harmless in terms of causing other people conflicts.

**Comment by albertjan** [comment]
Do you want to wait till after @waywaaard's big PR or are you ready to merge this? It looks good to me but I might not be the best person to review it. I haven't done much with modules and packages. And there aren't many unit tests covering these packages.

**Comment by waywaaard** [comment]
Do we have some unittests that assert the correct loading of files and all supported variations of the import statement?

**Comment by albertjan** [comment]
I looked through the test there are loads of tests that use these packages. These all keep working. So afaic __LGTM__, shall I merge @bnmnetp or do you want someone else to look at it? Maybe @bzwheeler?

**Comment by bzwheeler** [comment]
Perhaps not hugely important but the "third party modules" portion of skulpt.org home page references an example of loading processing dynamically and it lists the path as:

```js
      processing : {
        path : 'processing/__init__.js',   // path to where the main file is located
```

Should we update this to reflect the change as well?

**Comment by albertjan** [comment]
I think we should :smile:

**Comment by bnmnetp** [comment]
actually updating this to point to something that is not in skulpt-stdlib.js would be a much better example.

**Comment by waywaaard** [comment]
I use it like this:

```javascript
        Sk.externalLibraries = {
            numpy : {
                path: '/static/primeronoo/skulpt/external/numpy/__init__.js',
                dependencies: ['/static/primeronoo/skulpt/external/deps/math.js'],
            },
            matplotlib : {
                path: '/static/primeronoo/skulpt/external/matplotlib/__init__.js'
            },
            "matplotlib.pyplot" : {
                path: '/static/primeronoo/skulpt/external/matplotlib/pyplot/__init__.js',
                dependencies: ['/static/primeronoo/skulpt/external/deps/d3.min.js'],
            },
            "arduino": {
                path: '/static/primeronoo/skulpt/external/arduino/__init__.js'
            }
        };
```

Examples for normal names, dotted and with/without dependencies

**Comment by bnmnetp** [comment]
Thanks, I updated the gist for that example.

**Comment by albertjan** [comment]
Is this also true for python modules?

**Comment by bnmnetp** [comment]
No. Only those not built in to skulpt-stdlib

Brad Miller, PhD
Associate Professor, Computer Science
Founder, Runestone Interactive
Blog: http://reputablejournal.com
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.1.51&pv=8.2]
On Tue, May 26, 2015 at 10:55 PM, skulpt/skulpt
<reply@reply.github.com>
wrote:
Is this also true for python modules?

—
Reply to this email directly or view it on GitHub
[https://github.com/skulpt/skulpt/pull/438#issuecomment-105661837] .[https://github.com/notifications/beacon/AADHqzMoj3pMhSDsZe3-aLHH7AktNwNCks5oNNVKgaJpZM4Epq0p.gif]

**Comment by bnmnetp** [comment]
@albertjan I did the merge test in both orders with no merge conflicts.  Git does a good job of tracking changes even across file renames.

**Pull request merged**
