### PR TITLE
skulpt function should be called with Sk.misceval.callsim

### PR DESCRIPTION
**Pull request by albertjan**
This should address #697

### CODE REVIEW

**Comment by bnmnetp** [comment]
Great, I'll pull this one and the super PR onto my test branch and give them a whirl.

**Comment by bnmnetp** [comment]
Yep, this fixes the problem, and doesn't break anything else AFAIK.

This one should be an easy accept.

**Comment by albertjan** [comment]
i don't think this code is used from anywhere else

**Comment by meredydd** [comment]
LGTM by inspection. Merging.

**Comment by meredydd** [comment]
FYI @albertjan, the canonical GitHub way of doing a pull request that closes an issue is to use a magic phrase like `fixes #697` or `closes #697` in a commit message. Then, when-and-only-when that commit is merged into master (ie when the PR is accepted), the issue will be closed with a link to the PR and commit responsible.

This avoids prematurely closing issues while the fix is still unmerged, while still making sure you don't have to remember it yourself!

**Pull request merged**
