### PR TITLE
Add `datetime` module

### PR DESCRIPTION
**Pull request by meredydd**
Once PRs #635 and #634 are applied, Skulpt can load and apparently run the `datetime` module from PyPy 5.1.0 (the only thing I had to take out was the pickle support, which used `struct`).

Obviously those older PRs should be reviewed first.

### CODE REVIEW

**Comment by albertjan** [comment]
:+1: 😄 not much to review in this one. I couldn't care less about pickle support :trollface: I say merge!

**Comment by meredydd** [comment]
Hold your fire on this one, please. There's some `__iadd__` weirdness going on with date arithmetic (+= doesn't work yet). The other two are good to go, though :)

**Comment by meredydd** [comment]
The in-place addition bug is now fixed separately in PR #657, so I'd now consider this clear to merge. Can I get a second +1?

**Comment by rixner** [comment]
Except for my issue with #635, I see no problem with this.  Once we agree to merge #634 and #635, I think this should be merged immediately.

**Pull request merged**
