### PR TITLE
Implement __slots__

### LINKED ISSUE #1050: Lack of  __slots__
Lack of `__slots__`.

### PR DESCRIPTION
**Pull request by s-cork**
This pr implements `__slots__`
it's 1 commit ahead of #1092 
For the diff see the last commit on this pr or you can check it out here: 590d8ac

It includes all the tests from cpython unittests (with a couple of edge cases commented out)

I also needed to implement `isidentifier` for `str`

The copy module does't work for classes that define `__slots__` but since `__slots__` previously wasn't supported, copying them wouldn't really have worked anyway.
(to fix the copy module we can look to define the `__reduce_ex__` descriptor)

closes #1050

### CODE REVIEW

**Comment by bnmnetp** [comment]
I would be happy to merge this in to my Fork and test it in my books. If it works on all my examples I would be in favor of merging this and moving forward.

 Could you take a quick look at the conflicts?

**Comment by s-cork** [comment]
sure  - i've merged into master and resolved those conflicts

There are a couple of gotcha's with this branch that might need some tweaks/discussion/feedback

`new` becomes required for all skulpt constructors and (currently) fails silently in production mode but loudly in development with `Sk.asserts`

```javascript
var myclass = Sk.misceval.buildClass('myclass', ($gbl, $loc) => {$loc.foo = 'bar'}, []);
myclass.foo  // undefined
myclass.prototype.foo // 'bar'
```

those two of the main breaking changes - but there are a number of others.

**Comment by meredydd** [comment]
FWIW, the current version of #1092 has been in production in Anvil for a few weeks now, and appears not to have broken any existing code. (It broke plenty of our internal JS code, but that's a separate matter!)

**Comment by bnmnetp** [comment]
@skulpt/committers someone want to approve this one too?  So much good stuff waiting in the wings....

I'm happy to be merger in chief but I'm not a compilers guy, the rest of you are way more qualified than I am to review these things.

**Comment by meredydd** [comment]
Reviewed and approved as part of #1244 :+1:

**Pull request merged**
