### PR TITLE
Update node packages and engines.

### PR DESCRIPTION
**Pull request by rixner**
#1004 uses ```BigInt``` which wasn't introduced into node until version 10.4.  Update engines in package.json.  Also update some other packages that npm complains have security issues.

### CODE REVIEW

**Comment by albertjan** [comment]
Ah sorry about that. I missed that. Weren't we already using a transparent polyfill for BigInt?

**Comment by rixner** [comment]
I don't think we use ```BigInt``` anywhere else...  Perhaps we now need a polyfill?  We've never really settled on what level of support we want for older browsers...

**Comment by albertjan** [comment]
Ah! I knew I had done this work somewhere. In my first attempt to update to node I had removed our biginteger.js and replaced it with a polyfill for BigInt. The browser support for BigInt is still very small so I think we'll have to do this I'll see if I can excavate that code and do a PR.

**Comment by albertjan** [comment]
https://caniuse.com/#search=bigint

**Comment by rixner** [comment]
Yeah, we definitely need a polyfill.  Pulling #1004 was premature. :)

If we have the polyfill, biginteger.js should go, so I hope you can extract that part easily!

**Comment by rixner** [comment]
I suspect it is going to be difficult to drop in ```BigInt``` with a polyfill, especially since you can't use a transparent polyfill.  While I think we should try to replace ```Sk.builtin.biginteger``` with ```BigInt```, I think that's a larger undertaking.  So, I replaced the use of ```BigInt``` in math.js with ```Sk.builtin.biginteger```.  I think that's the easier/better short term solution.

I favor pulling this quickly so that we can get back to being compatible with all browsers (Safari, I'm looking at you) and then if someone is excited about doing so, we can replace ```Sk.builtin.biginteger``` with ```BigInt``` somehow with an appropriate polyfill in another pull request.

I'm leaving the node engines declaration at 10.4, but can reset it to 8.10 if people think that's the right thing to do.

**Comment by albertjan** [comment]
@rixner see: https://github.com/skulpt/skulpt/pull/857/commits/6f07236faf6cbadfbce7b387c9feda0cd8bd5540

**Comment by rixner** [comment]
@albertjan that looks good.  I didn't realize you found one that has the same interface we already use.  That isn't "transparent" in the sense that we still can't have code directly using ```BigInt``` like math.js does, so math.js still needs to be "fixed" as I did here.


I do believe we all discussed this in the past and JSBI was suggested instead, because babel can convert it directly to ```BigInt``` once there is universal support and we no longer want a polyfill.  I'll try to dig up that conversation. 

How do you want to proceed?

**Comment by rixner** [comment]
(Also we can't require/import node packages in libraries, so whatever polyfill we use will have to be exported via ```Sk``` in order for math.js to be able to use it.)

**Comment by rixner** [comment]
The previous discussion (#729) wasn't as extensive as I had remembered.  @albertjan you and I agreed we should use a polyfill, and then we didn't. :smile:

**Comment by rixner** [comment]
@albertjan, using your code as a guide, I updated everything to use ```big-integer``` and it seems to work fine with the dev build.  However, the closure compiler does not like the ```big-integer``` library, so I can't do a production build.  Not sure what to do at this point...

**Comment by rixner** [comment]
See my [bigint branch](/rixner/skulpt/tree/bigint).

**Comment by albertjan** [comment]
wow @rixner that's a lot of errors

**Comment by s-cork** [comment]
Nice job @rixner Sorry for the small headache I caused 🤕 ... still learning ... 📘 ✏️

**Comment by rixner** [comment]
@s-cork no problem - the reviewers missed it too!  This pull request fixes it, so no real damage was done.  The "headache" is in getting a library/polyfill to work, which is entirely unrelated, as far as I'm concerned.

**Comment by rixner** [comment]
@albertjan yeah, I was surprised.  I think the only way to get it to work is to not run it through the closure compiler.  That's a level of webpack/closure gymnastics that I'm not sure I want to undertake.  I'm going to look a little bit at other libraries.

**Comment by albertjan** [comment]
there must be a way to tell closure this is an external dependency and it shouldn't be typechecked

**Comment by rixner** [comment]
JSBI is no better closure-wise.  I'll see if I can get closure to skip big-integer.

**Comment by rixner** [comment]
I am unable to get it to work at this point.  Both webpack and the closure compiler have the notion of externals and third party libraries, but I can't find the right set of magic incantations to get everything to build.  

One initial problem is that ```BigInteger.js``` is under a node package called ```big-integer```.  The dash can't be used in a valid Javascript identifier, which bedevils webpack.  Even if I move the file itself and just work with that, I still run into mystifying errors from the closure compiler.

Unless anyone else knows how to get this all to work, I'd like to just get this pull request merged so that we are back to being browser compatible and someone else can take a run at a BigInt library and hopefully have better luck than I am...  At this point, I'm stuck and don't have additional time to work on it.

**Comment by s-cork** [comment]
is this relevant at all?  https://github.com/google/closure-compiler/issues/3167

**Comment by albertjan** [comment]
Alright lets merge this first and figure out how to deal with the polyfill later. Maybe @meredydd has an idea.

**Comment by rixner** [comment]
I'll come back to this at some point, as well, but I don't think we should block this merge until that happens...

@s-cork that does reinforce that we can't run the library through the closure compiler, but I was trying (unsuccessfully) to not run it through the closure compiler for other reasons.

**Comment by rixner** [comment]
I figured out the problem.  And it's not good.

In ```biginteger.js``` we have a ```@supress {checkTypes}``` directive.  That was turning off the closure compiler's type checking for code outside that file.  When I stopped including that file, I started getting errors all over the place, because the closure compiler is now actually type checking all of the code.  So, it's not that I was doing the wrong thing in terms of the big integer library, but rather that we have a lot of latent type errors that get exposed.  I'm not sure where to go with that.

**Comment by rixner** [comment]
There are a bunch of issues with the ast and type checking.  I am wondering if some of the cleanup in #991 would help...

There are also several legitimate errors, rather than just incomplete/bad type annotations on our part, that closure is catching.  I don't know why they don't cause perceivable problems.

**Comment by rixner** [comment]
I'm down to 17 errors from the closure compiler, which is significantly better than where things started.  I will see if I can get rid of any more, but a good deal of them are references to AST nodes and Tokens that are just not defined anywhere.  I'm not sure if they used to be defined and we lost them somewhere along the line or if there's speculative code that assumes they'll be implemented some day or what...  Presumably I could delete them without any negative impact since they're not doing anything useful, but I'm not sure if that's the right approach.

Examples:  T_BACKQUOTE, Sk.astnodes.Repr, exec_stmt

**Comment by rixner** [comment]
I believe I have eliminated all of the closure compiler errors (maybe not in the best way possible), but I have as of yet been unable to get it to rebuild a working ```skulpt.min.js```.  The issues have to do with webpack and splitting and merging the files.  It still works with the devbuild so I don't think the issue is that I broke the code, I really think it's just not bundled correctly anymore.

Webpack also injects some code that has (1) closure compiler errors in it and (2) references to ```window``` which won't work in node.  I don't know that there's any way around that other than to modify the webpack source, which is less than desirable.  As a test, I did modify the webpack source to eliminate (1) and then tried to run the result in a browser, where ```window``` should work, but that wasn't working for me either.

At this point, I think we should just merge this pull request.  We do have the somewhat serious issue, though, that the closure compiler is not doing type checking anywhere, as far as I can tell.  So, we have to resolve that (in my opinion), whether we use a big integer library or not.

So, @skulpt/committers please merge this so that we regain browser compatibility while we work out the other issues (or ignore them, I guess)!

**Comment by albertjan** [comment]
@rixner did you forget to push to this branch? Or do you want to update the type stuff in a different PR.

**Comment by rixner** [comment]
@albertjan I have another PR that I'll submit after this one with my fixes (including the type stuff).  I have it "working" now.  But, that's going to require careful review and discussion, whereas this does not.  Let's merge this, which is the minimum to get back to where we were, and then I'll open that one.

**Pull request merged**
