### PR TITLE
Fix dotted imports

### PR DESCRIPTION
**Pull request by meredydd**
Looks like #833 broke imports deeper into heirarchies, and our test suite didn't catch it. Oops. It broke Anvil pretty hard, though, and will probably other people using current master too, so let's get this merged and restore my honour ;)

This PR adds tests that would have noticed this bug, and then fixes it.

### CODE REVIEW

**Comment by albertjan** [comment]
✅ honor restored

**Comment by rixner** [comment]
While I don't think it matters for this pull request, but have we given up on 2 people approving a pull request before we accept it?  (To be clear, I was about to approve this one and am not quibbling with its acceptance.)

**Comment by bnmnetp** [comment]
I think we said something like for relatively minor changes if a committer and one other reviewer agreed that it was OK to merge with just one review.

I worry a little bit that the two review policy was the start of the great slowdown in progress on the master branch.  It is easier to keep your own fork moving forward if PRs are languishing on master.  I don't think that the master should be a dumping ground, but I do think we make better progress if changes get onto master quicker for others to take advantage of.  We may just need to get to a place where we are tagging actual solid release points.

**Comment by meredydd** [comment]
I agree with @bnmnetp that the "two-reviewer rule" appears to have slowed us down a lot. (Also that this particular fix didn't need two reviewers even under our existing rules.)

I think for most (small-to-medium-sized) changes authored by a maintainer, (especially with tests that exercise the functionality), one review from another maintainer should suffice - ie the author can count as one of the two reviewers.

But perhaps that's just selfish - it would unblock us personally, but we might still end up with third-party PRs languishing forever.

**Comment by bnmnetp** [comment]
This all started with #414 -- which is still open... Maybe we should continue this discussion there to decide if we want to streamline things a bit now that we have some momentum again!

**Pull request merged**
