### PR TITLE
check for x32 sudir on windows

### PR DESCRIPTION
**Pull request by bnmnetp**
Can someone with windows give this a quick test.  It should satisfy those with a newer / different d8 installation on windows and what the rest of us have.

### CODE REVIEW

**Comment by bnmnetp** [comment]
can someone on @skulpt/committers or @waywaaard  give this a quick try to verify that it works on windows for you now.

**Comment by albertjan** [comment]
I was trying @appveyor today but the build takes ages to start so I didn't finish it. 

I'll have some time tomorrow. I can at least check. :)

**Comment by waywaaard** [comment]
Working for me :)

**Comment by albertjan** [comment]
You were up early! :)

**Pull request merged**
