### PR TITLE
Named Tuple

### PR DESCRIPTION
**Pull request by s-cork**
### syntax implemented namedtuples in 3.7 
```python
collections.namedtuple(typename, field_names, *, rename=False, defaults=None, module=None)
```

#### `defaults`
```python
>>> Point = namedtuple('Point', 'x, y', defaults=[2])
>>> Point(3)
Point(x=3, y=2)
>>> Point = namedtuple('Point', 'x, y', defaults=[1,2])
>>> Point()
Point(x=1, y=2)
>>> Point(5)
Point(x=5, y=2)
```

#### `rename`
```python
>>> A = namedtuple('A', 'abc, def', rename=True)
>>> A(1,2)
A(abc=1, _1=2)
>>> A = namedtuple('A', '1, 2, 3', rename=True)
>>> A('a', 'b', 'c')
A(_0='a', _1='b', _2='c')
```

#### `kwargs`
```python
>>> Point = namedtuple('Point', 'x, y')
>>> Point(3, 4)
Point(x=3, y=4)
>>> Point(x=3, y=4)
Point(x=3, y=4)
```

#### `_asdict`, `_fields`, `_field_defaults` 
```python
>>> Point = namedtuple('Point', 'x, y', defaults=[2])
>>> p = Point(3)
>>> p._asdict()
{'x': 3, 'y':2}
>>> p._fields
('x','y')
>>> p._field_defaults
{'y':2}
>>> Point._fields
('x', 'y')
>>> Point._field_defaults
{'y':2}
```

> **Q: `_asdict` returns a `dict` in 3.8 since dicts are ordered in 3.6+, where as, `_asdict` in 3.7 or below returns an `ordereddict` I went with `dict` since the implementation is easier... does that seem sensible?**

#### `_make`
```python
>>> Point = namedtuple('Point', 'x, y', defaults=[1,2])
>>> p = Point()
>>> p._make([3,4])
Point(x=3, y=4)
>>> Point._make([3,4])
Point(x=3, y=4)
```

#### `__new__`
```python
>>> Point = namedtuple('Point', 'x, y', defaults=[1,2])
>>> Point.__new__(tuple, 3,4)
(3, 4)
```

### subclassing
```python
>>> Point = namedtuple('Point', 'x, y', defaults=[1,2])
>>> class Q(Point):
...    pass
...
>>> p = Q(4, 6)
>>> p.x
4
```

---

### CODE REVIEW

**Comment by s-cork** [comment]
meant to make this a draft sorry!

**Comment by s-cork** [comment]
Any support on this one would be great! 😅

**Comment by s-cork** [comment]
@meredydd , @albertjan , @rixner  - I think this is read for review whenever you get a chance.

Thanks in advance!

**Comment by s-cork** [comment]
@albertjan - an fyi that Travis still seems to be misbehaving. There's a few other pull requests (e.g. #1044) where Travis hasn't kicked in.

**Comment by alexwenbj** [comment]
Hi,@s-cork ,firstly, thank you for your great job. Although it is not merged yet, but I have a try in my own build,the code is as below:(it is from https://www.geeksforgeeks.org/namedtuple-in-python/)
```
# importing "collections" for namedtuple() 
import collections 
  
# Declaring namedtuple() 
Student = collections.namedtuple('Student',['name','age','DOB']) 
print(type(Student))
  
# Adding values 
S = Student('Nandini','19','2541997') 
print(type(S))
# Access using index 
print ("The Student age using index is : ",end ="") 
print (S[1]) 
  
# Access using name  
print ("The Student name using keyname is : ",end ="") 
print (S.name) 
```
But I got an error in the last line:
'Student' object has no attribute 'name_$rn$'

Can you check what is the problem for this?
Thank you again.

**Comment by s-cork** [comment]
> But I got an error in the last line:
> 'Student' object has no attribute 'name_$rn$'
> 
> Can you check what is the problem for this?
> Thank you again.

Thanks for spotting.

Interesting - it looks like it's something to do with skulpt mangling certain reserved words. I get the same error running both this PR and Master branches - so I don't think this PR introduced this bug thankfully. 🙏 

I'll have a play with the code and see what I can come up with. 

another example of this... 
```python
>>> class A:
...   pass
...
>>> a = A()
>>> a.name = 'foo'
>>> a.bar = 'foo'
>>> 'name' in dir(a)
False
>>> 'bar' in dir(a)
True
>>> a.name
'foo'
```

**Comment by s-cork** [comment]
@alexwenbj  - fixed the issue and added some tests. 
It should work (mostly) as expected. 

Some other skulpt bugs I discovered along the way:
- mangled names don't appear in the directory 
- getattr doesn't work on mangled names
e.g.
```
>>> class A:
...   pass
...
>>> a = A()
>>> a.name = 'foo'
>>> 'name' in dir(a)
False
>>> getattr(a, 'name')
'klass'
```
I might see if these bugs are easily fixed in this PR but maybe not...

**Comment by alexwenbj** [comment]
@s-cork Great!Thank you.

**Comment by s-cork** [comment]
created a separate pull request for the `getattr` and `dir` issue #1070

**Comment by s-cork** [comment]
FYI no need to review this one - I will strap it onto #1070 
it becomes a lot nicer when `tp$new` is a skulpt slot and `property` is a javascript implementation.

**Pull request merged**
