### PR TITLE
Add p5.js module

### PR DESCRIPTION
**Pull request by nickmcintyre**
Hello! I'm working on a [p5.js](https://p5js.org/) module for my courses and thought I'd contribute it as a step forward on #695. A simple version of the module already runs just fine, and I think it would be straightforward to more closely align it with either the Processing.py or p5.js API's.

### CODE REVIEW

**Comment by nickmcintyre** [comment]
@s-cork's work on a new ffi API makes this job *much* simpler... hope it gets merged sooner than later.

I'm more than happy to complete a version of the p5 module based on the existing ffi as a stop-gap measure.

**Comment by alexwenbj** [comment]
It seems lack of size(w,h)?And any step-forward plan for this lib?
Thank you.

**Comment by s-cork** [comment]
@alexwenbj worth looking at #1191 which has a wrapper around the p5 library

**Comment by alexwenbj** [comment]
@s-cork Thank you. And i look forward to all the unmerged pr to be merged soon, especially slots/new ffi etc.

**Comment by swirly** [comment]
The pull request seems to be too old now. Nobody can review it ?
Nobody wants to update the PR?

**Comment by nickmcintyre** [comment]
@swirly I'm happy to complete the custom wrapper over the next couple of weeks if there's still interest.

@alexwenbj If I do move forward with the p5 module, do you have guidance on whether the API should align more closely to Processing.py or p5.js?

**Comment by alexwenbj** [comment]
> @swirly I'm happy to complete the custom wrapper over the next couple of weeks if there's still interest.
> 
> @alexwenbj If I do move forward with the p5 module, do you have guidance on whether the API should align more closely to Processing.py or p5.js?

No, I still use the processing by now, but I am willing to use it if it is implemented. Thank you for your work.

**Comment by s-cork** [comment]
Given that we're trying to keep the core of Skulpt closer to CPython I think we should close this

I assume @nickmcintyre  you're using this somewhere and have it working
Maybe the best thing to do for projects like this is to link them somewhere
Either on the website or the readme
If it's the readme then under a heading like `External Libraries`

**Comment by nickmcintyre** [comment]
@s-cork thanks again for your help with this!

It turns out that the Raspberry Pi Foundation is using Skulpt and portions of [p5.sk](https://github.com/nickmcintyre/p5.sk) in their [Introduction to Python](https://projects.raspberrypi.org/en/projects/target-practice-editor) path and their [new editor](https://editor.raspberrypi.org/en/). Patrick Cherry and Scott Adams mentioned open-sourcing the work, so you might contact them about a link.

**Pull request closed without merging**
