### PR TITLE
fix args.length check, add tmp.js to .gitignore

### PR DESCRIPTION
**Pull request by d4rkb1ue**
turtle.js args.length check missing the a `.length` thus can't throw an error on args missing

### CODE REVIEW

**Comment by albertjan** [comment]
Hey thanks for your contribution, the build is failing because it's using npm5 which doesn't work with our antquated version of node. Could you change this line: https://github.com/skulpt/skulpt/blob/master/.travis.yml#L6 to say :`- npm install npm@4 -g`? The build should be fixed then... I hope.

**Comment by j-f1** [comment]
@albertjan What version of Node are you using? Why can’t you upgrade?

**Comment by albertjan** [comment]
We should be able to upgrade but that would mean figuring some stuff out, which is kind of out of scope of this PR.

**Comment by albertjan** [comment]
Thanks @d4rkb1ue

**Pull request merged**
