### PR TITLE
Bugfix dir (also removes __name__ from output)

### PR DESCRIPTION
**Pull request by Jacco**
#452

### CODE REVIEW

**Comment by albertjan** [comment]
Could you also add a test for this?

**Comment by bnmnetp** [comment]
test/run/t407.py incompletely tests the operation of dir, in that the tests do not check for inherited methods.

**Comment by bnmnetp** [comment]
You can just add this to the current test_builtin.py  and see what happens.  Some things may need to be commented out and filed as further fixes required.

**Comment by Jacco** [comment]
A *LOT* of fixes are required...

- dir can be called without parameters then is gets local definitions
- one test subclasses a Module replaces __dir__ and tests (modules cannot be subclassed yet and __dir__ is not handled yet)
- exit is not in sys
- strip is not in string

And more

**Comment by albertjan** [comment]
Ah :smile: maybe it'd be better if  you just added a test that shows the inherited functions.

**Comment by albertjan** [comment]
LGTM!

**Comment by eah13** [comment]
I added string methods and sys.exit to #400.  Subclassing built-ins is already on there.

Aside: Wonder if we need a test task force to knock out little things like these preventing use of Python's tests as they come up. That way it's not an extra burden on specific PRs but progress gets made towards a better testing future. :notes: :notes:

**Comment by Jacco** [comment]
This PR fixed #449 so it can be closed :-)

**Pull request merged**
