### PR TITLE
add py3/py2 switch to commandline repl

### PR DESCRIPTION
**Pull request by albertjan**
Adds `py2` or `py3` as required parameter to `npm run repl`

```
➜  skulpt git:(master) ✗ npm run repl    

> skulpt@1.0.0 repl /Users/albertjan/skulpt
> node repl/repl.js

Using skulpt.min.js
error: must specify python version (py2/py3) and python program to run
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skulpt@1.0.0 repl: `node repl/repl.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the skulpt@1.0.0 repl script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/albertjan/.npm/_logs/2020-05-25T12_45_56_434Z-debug.log
➜  skulpt git:(master) ✗ npm run repl py2

> skulpt@1.0.0 repl /Users/albertjan/skulpt
> node repl/repl.js "py2"

Using skulpt.min.js
Python 2.7(ish) (skulpt, Mon May 25 2020 13:45:59 GMT+0100 (British Summer Time))
[node: v10.16.0] on a system
Don't type "help", "copyright", "credits" or "license" unless you've assigned something to them
>>> print "hello" 
hello
>>> ^C
➜  skulpt git:(master) ✗ npm run repl py3

> skulpt@1.0.0 repl /Users/albertjan/skulpt
> node repl/repl.js "py3"

Using skulpt.min.js
Python 3.7(ish) (skulpt, Mon May 25 2020 13:46:09 GMT+0100 (British Summer Time))
[node: v10.16.0] on a system
Don't type "help", "copyright", "credits" or "license" unless you've assigned something to them
>>> print "hello"
SyntaxError: bad input on line 1
1>: print "hello"
>>> ^C
```

@s-cork please review 😄 

Fixes: #1031

### CODE REVIEW

**Comment by s-cork** [comment]
the fix for the issue is this line
```
lines.push("if not evaluationresult == None: print repr(evaluationresult)");
```

suggestion: 
```javascript
if (Sk.__future__.python3) {
    console.log("Python 3.7(ish) (skulpt, " + new Date() + ")");
    evaluationresult = "if not evaluationresult == None: print(repr(evaluationresult))";
} else {
    console.log("Python 2.7(ish) (skulpt, " + new Date() + ")");
    evaluationresult = "if not evaluationresult == None: print repr(evaluationresult)";
}

...

            if (!re.test(lines[0])) {
                                //remove the statement
                //evaluate it if nessecary
                lines.push("evaluationresult = " + lines.pop());
                //print the result if not None
                lines.push(evaluationresult);
            }
```

**Comment by s-cork** [comment]
there's also a weird quirk that i'm but it seems to be there on master too. So I guess it's not really required for this pr...

```
>>> class A: pass
>>> A
<class '__builtin__.classmethod.A'>
>>> __name__
__builtin__
```

something to do with  `property`, `classmethod` and `staticmethod` being the last imports 🤔

**Comment by albertjan** [comment]
Wow 🤦‍♂️ sorry about that 😄.

And yeah we have some shared state in import.js I think that causes this, I've seen it before but never bothered to dive into it. import.js is a bit of a hairy beast.

**Comment by albertjan** [comment]
@skulpt/committers have at it 😄

**Pull request merged**
