### PR TITLE
Added jsdoc output

### PR DESCRIPTION
**Pull request by eah13**
~~**Update: waiting on #479 to get merged before this will be ready for review.**~~ Ready for Review.

This PR puts some jsdoc-generated docs in a `docs` folder.  The `docs` folder is automatically rendered by Jekyll in a /docs/ subdirectory of the site.  See it deployed [here](http://elliotthauser.com/skulpt/docs/)

The following has also been added to the `gh-pages` readme:

The `docs` folder is generated by jsdoc.  Instead of editing it, each time one of the underlying js files or the HACKING.rst file is changed:                           
                                                                                                                                                                        
1. `git checkout master` if you're not already there                                                                                                                    
2. `npm install -g jsdoc` if you haven't already                                                                                                                        
3. `./skulpt.py doc` to generate the docs in `doc/ProgMan`                                                                                                              
                                                                                                                                                                        
The generated HTML is now in a folder called `doc/ProgMan` that's in your git working tree                                                                                                                     
                                                                                                                                                                        
4. `git checkout gh-pages` then `git checkout -b new-branch-name`.  Or checkout your pre-existing branch made from `gh-pages`                                           
6. `rsync -r doc/ProgMan docs` then `rm -rf doc`                                                                                                                        
7. `git diff .` to see the changes, `git add .` to add them, `git commit -m "Commit message here"`                                                                      
                                                                                                         

:boom: Instant docs.

### CODE REVIEW

**Comment by eah13** [comment]
There seems to be less documentation that I'd expect here.  @bnmnetp, did I run `jsdocs` incorrectly here?

**Comment by bnmnetp** [comment]
No, you need the changes in the pr that is open for the reference manual

**Comment by albertjan** [comment]
@eah13 merged #479

**Comment by eah13** [comment]
@bnmnetp @albertjan sweet!  much better. See it live here: http://elliotthauser.com/skulpt/docs/

screenshot 2015-06-08 at 5 42 44 pm

**Comment by bnmnetp** [comment]
@eah13,  If you use the ./skulpt.py doc command it will use jsdoc -c jsdoc.conf HACKING.md as the command, and the build should include the Sk.importMainWithBody documentation too.

**Comment by eah13** [comment]
Killer.  Done now and the new changes are deployed for easy review http://elliotthauser.com/skulpt/docs/

**Pull request merged**
