### PR TITLE
creates a suspension from a promise

### PR DESCRIPTION
**Pull request by albertjan**
I finally broke and wrote this. This turns a promise into a suspension.

@meredydd I fully expect you to say I'm doing it all wrong .

### CODE REVIEW

**Comment by albertjan** [comment]
Well no I haven’t I was interrupted by dinner :P. What do you mean with renamed the variable?

________________________________

**Comment by meredydd** [comment]
We call it `newSuspension`. You call it `susp` (and `suspension`, apparently ;) ). Other than that, that's the same code we use :)

**Comment by albertjan** [comment]
There it builds and I've even scrubbed the history of my faux pas.

**Comment by meredydd** [comment]
Does Closure understand the `let` statement and compile it to vanilla IE-compatible Javascript?

(I agree that it would be good to be able to use modern features like `let` in Skulpt, but to do that we'll need tooling that allows us to support those older browsers...)

**Comment by albertjan** [comment]
The version of closure or v8 we use don't support `let` it doesn't compile. And yes, I love all the new javascript niceties, and I'd love to use them in skulpt too. This was copied from a side project, which uses babel and rollup to do the compiling.

**Comment by meredydd** [comment]
Minor change, merging.

**Comment by bnmnetp** [comment]
How closely related to #666 is this issue?  Is there a version of closure that is compatible with let and other es6 goodness??

**Comment by albertjan** [comment]
I don't know @bnmnetp but it might be worth looking into 😄

**Comment by bnmnetp** [comment]
The closure compiler wiki says:

ECMAScript 6 is now officially supported as an input language for the Closure Compiler. You cannot use it as an output language yet; for now you need to transpile down to ES5 or ES3. If you find that the Closure Compiler does not support your favorite ES6 feature, you can file an issue, but please be aware that supporting the entire ES6 specification is a non-goal for the Closure Compiler.

They have a nice list of features that are supported on the input:  https://github.com/google/closure-compiler/wiki/ECMAScript6

**Comment by albertjan** [comment]
OHhhh this is really nice!

**Comment by meredydd** [comment]
YES. Propose we start doing ES6 right away.

**Pull request merged**
