### PR TITLE
Fixes imports that are own files but show up in the from list

### LINKED ISSUE #299: package import bugs
Given the directory structure:

```
test/
   __init__.py
   test_support.py
```

The following import statement fails:  ``from test import test_support``

However this one works:  ``from test.test_support import run_unittests``

We need to fix this behavior otherwise we are going to have to modify all of the CPython unit tests to import the ``run_unittests`` function.

### PR DESCRIPTION
**Pull request by waywaaard**
Should fix #299 .

Example:

```python
from unittest import gui as mystuff

print("nothing to see here")
print(dir(mystuff))
```

### CODE REVIEW

**Comment by albertjan** [comment]
@meredydd what do you think about this. It looks good to me. Pretty important missing feature.

**Comment by meredydd** [comment]
I'm afraid I just timed out on Skulpt stuff for now; I can't review this properly within the next week at least :-/

**Comment by albertjan** [comment]
Alright :smile:

**Comment by eah13** [comment]
Looks good to me

**Pull request merged**
