### PR TITLE
fix reserved words in get and set attr

### PR DESCRIPTION
**Pull request by albertjan**
Use the same reserved words mangler for `get/setattr` as the compiler uses. So we can use `get/setattr` to get fields like `default` and `delete` from objects.

### CODE REVIEW

**Comment by rixner** [comment]
Are there tests for this?  If not, can you add some?

**Comment by albertjan** [comment]
Of course.

**Comment by rixner** [comment]
This looks good.

My only concern here is the "unmangling".  Should we have a function (```unfixReservedWords``` or something) to do that in case we need to change the mangling in the future?  That way, the fix and "unfix" could be in the same place, so one didn't need to hunt through the code to find places that needed to change?

This is a legitimate question of mine.  I'm not saying this shouldn't be merged without that change.

**Comment by albertjan** [comment]
I agree threre is currently no such function but it's easily added, I'll do
that :).

**Comment by rixner** [comment]
I say merge.

**Pull request merged**
