### PR TITLE
fix the color function for arguments length

### PR DESCRIPTION
**Pull request by alexwenbj**
See: #891  and #850

### CODE REVIEW

**Comment by bnmnetp** [comment]
@alexwenbj what problem are you trying to fix here?

We should be able to call color (too) many different ways
```
color() --> returns the current colors
color(string) set color and fillcolor
color(string,string) set color and fillcolor
color((tuple), (tuple))
color((tuple))
color(num,num,num) where num is either an int or a float and works depending on cmode
```
I think I have them all. It would be good to document what you are fixing and probably put something into the code to make it clear what is trying to handle which cases.

**Comment by alexwenbj** [comment]
You can try color("red","yellow"),because the `arguments.length` is 5,so the condition `arguments.length>=3` is met,and it will call` createColor(this._colorMode, color, fill, b, a)`,it is not correct here.

**Comment by alexwenbj** [comment]
By the way,why the color()/fillcolor()/pencolor() function have 4 arguments?In Python,they have at most 3 arguments.

**Comment by albertjan** [comment]
@bnmnetp this is the same problem you fixed before. I think this is good to merge. 😄

**Pull request merged**
