### PR TITLE
Continue in while loop if return is pressed

### PR DESCRIPTION
**Pull request by eah13**
Still behaviors in the repl that don't match Python's but this small fix will avoid a nasty error for a common behavior: pressing return on an empty prompt.

### CODE REVIEW

**Comment by albertjan** [comment]
LGTM. Do you want to change it in `/doc/static/repl.js` too? I know I know it isn't very dry :smile:

**Comment by eah13** [comment]
Ooh cool I didn't know that was there.  Well gross, kinda, but now I know where all that HTML lives

I think I'll win the award for tiniest pull requests.  Start small, they say...

**Comment by albertjan** [comment]
Too quick :smile: the site repl is in a callback it's more of a cepl :tongue: So there it should be `return;`.

**Comment by eah13** [comment]
Bonus: I actually tested the web REPL this time.  Works great now.  thx for catching that.

**Pull request merged**
